name: grocery_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.2
  http: ^1.3.0
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/grocery+_logo.png
    - assets/images/cheese.png
    - assets/images/milk.png
    - assets/images/chicken.png
    - assets/images/egg.png
    - assets/images/lettuce.png
    - assets/images/tomato.png
    - assets/images/alfredo.png
    - assets/images/bell_peppers.png
    - assets/images/chicken_salad.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
